//! `swap` defines the functions for interacting with
//! the HTTP Swap API.

pub const SWAP_CREATE_ERROR_CODES: &'static [&'static str] = &[
    "INVALID_DEBIT_AMOUNT",
    "INVALID_CREDIT_AMOUNT",
    "SWAPPING_DISABLED",
    "TOO_MANY_FUTURE_SIGNATURES",
    "WRONG_NUMBER_OF_SIGNATURES",
    "DEBIT_WALLET_NOT_ADMITTED",
    "CREDIT_WALLET_NOT_ADMITTED",
    "DEBIT_CREDIT_WALLET_ADDRESS_MISMATCH",
    "DEBIT_CREDIT_TOKEN_ADDRESS_MATCH",
    "TOKEN_PAIR_BLOCKED",
    "EON_NUMBER_OUT_OF_SYNC",
    "DEBIT_WALLET_CANNOT_ADD_TRANSACTION",
    "CREDIT_WALLET_CANNOT_ADD_TRANSACTION",
    "DEBIT_WALLET_OVERSPENDING",
    "DEBIT_WALLET_BALANCE_AMOUNT_MISMATCH",
    "CREDIT_WALLET_BALANCE_NOT_ZERO",
    "INVALID_DEBIT_BALANCE_SIGNATURE",
    "INVALID_CREDIT_BALANCE_SIGNATURE",
    "INVALID_FUTURE_CREDIT_SIGNATURE",
    "INVALID_CREDIT_SIGNATURE",
    "INVALID_FUTURE_DEBIT_SIGNATURE",
    "INVALID_DEBIT_SIGNATURE",
    "INVALID_FUTURE_CREDIT_FULFILLMENT_SIGNATURE",
    "INVALID_CREDIT_FULFILLMENT_SIGNATURE",
];

pub const SWAP_CANCEL_UPDATE_ERROR_CODES: &'static [&'static str] = &[
    "WRONG_NUMBER_OF_DEBIT_SIGNATURES",
    "WRONG_NUMBER_OF_CREDIT_SIGNATURES",
    "SWAP_NOT_FROZEN",
    "SWAP_ALREADY_CLOSED",
    "MISSING_FREEZING_SIGNATURE",
    "SWAP_ALREADY_CANCELLED",
    "INVALID_CREDIT_SIGNATURE",
    "INVALID_FUTURE_CREDIT_SIGNATURE",
    "INVALID_DEBIT_SIGNATURE",
    "INVALID_FUTURE_DEBIT_SIGNATURE",
];

pub const SWAP_FINALIZE_UPDATE_ERROR_CODES: &'static [&'static str] = &[
    "SWAP_NOT_FULFILLED",
    "SWAP_ALREADY_FROZEN",
    "SWAP_ALREADY_VOIDED",
    "SWAP_ALREADY_CLOSED",
    "SWAP_ALREADY_FINALIZED",
    "WRONG_NUMBER_OF_CREDIT_SIGNATURES",
    "INVALID_CREDIT_SIGNATURE",
    "INVALID_FUTURE_CREDIT_SIGNATURE",
];

pub const SWAP_FREEZE_UPDATE_ERROR_CODES: &'static [&'static str] = &[
    "SWAP_ALREADY_FULFILLED",
    "SWAP_ALREADY_FROZEN",
    "SWAP_ALREADY_VOIDED",
    "SWAP_ALREADY_CLOSED",
    "INVALID_FREEZING_SIGNATURE",
];
