//! `transfer` defines the functions for interacting with
//! the HTTP Transfer API.

pub const TRANSFER_CREATE_ERROR_CODES: &'static [&'static str] = &[
    "INVALID_DEBIT_AMOUNT",
    "CREDIT_WALLET_NOT_ADMITTED",
    "DEBIT_WALLET_NOT_ADMITTED",
    "DEBIT_CREDIT_WALLET_ADDRESS_MATCH",
    "EON_NUMBER_OUT_OF_SYNC",
    "DEBIT_WALLET_EXCEEDED_SLA",
    "CREDIT_WALLET_EXCEEDED_SLA",
    "DEBIT_WALLET_CANNOT_ADD_TRANSACTION",
    "CREDIT_WALLET_CANNOT_ADD_TRANSACTION",
    "DEBIT_WALLET_OVERSPENDING",
    "DEBIT_WALLET_BALANCE_MARKER_EXCEED_BALANCE",
    "INVALID_DEBIT_BALANCE_SIGNATURE",
    "INVALID_DEBIT_SIGNATURE",
];

pub const TRANSFER_UPDATE_ERROR_CODES: &'static [&'static str] = &[
    "TRANSFER_ALREADY_APPROVED",
    "TRANSFER_TIMED_OUT",
    "CREDIT_WALLET_EXCEEDED_SLA",
    "CREDIT_WALLET_CANNOT_ADD_TRANSACTION",
    "INVALID_CREDIT_SIGNATURE",
];
